-- USER: SRC_USER - owns all source tables
-- These statements must be executed as SYS or with DBA privileges

CREATE USER SRC_USER IDENTIFIED BY src_password;
GRANT CONNECT, CREATE TABLE TO SRC_USER;

-- USER: TGT_USER - owns all target tables and views
CREATE USER TGT_USER IDENTIFIED BY tgt_password;
GRANT CONNECT, CREATE TABLE, CREATE VIEW TO TGT_USER;
GRANT CREATE PROCEDURE TO TGT_USER;

-- TEMA TABLES SQL: Full Schema Setup Script
-- Purpose: Initializes schema for employee activity tracking

--  Drop All Existing Tables
DROP TABLE TARGET_FACT_EMPLOYEE_ACTIVITY CASCADE CONSTRAINTS;
DROP TABLE TARGET_DIM_EMPLOYEE_HISTORY CASCADE CONSTRAINTS;
DROP TABLE TARGET_DIM_ABSENCE_TYPE CASCADE CONSTRAINTS;
DROP TABLE TARGET_DIM_DATE CASCADE CONSTRAINTS;
DROP TABLE TARGET_DIM_PROJECT CASCADE CONSTRAINTS;
DROP TABLE TARGET_DIM_EMPLOYEE CASCADE CONSTRAINTS;
DROP VIEW V_EMPLOYEE_PROFILE;
DROP TABLE SOURCE_ACTIVITY_TEMP CASCADE CONSTRAINTS;
DROP TABLE SOURCE_TRAINING_TEMP CASCADE CONSTRAINTS;

-- Drop Sequences
DROP SEQUENCE SEQ_EMPLOYEE;
DROP SEQUENCE SEQ_PROJECT;
DROP SEQUENCE SEQ_DATE;
DROP SEQUENCE SEQ_FACT_ACTIVITY;
DROP SEQUENCE SEQ_ABSENCE_TYPE;
DROP SEQUENCE SEQ_HISTORY;

-- Create Dimension Tables

CREATE TABLE TARGET_DIM_EMPLOYEE (
    EMPLOYEE_ID         NUMBER PRIMARY KEY,
    FULL_NAME           VARCHAR2(100),
    EMAIL               VARCHAR2(100),
    ACTIVE              CHAR(1),
    LEGACY_EMPLOYEE_ID  NUMBER
);

CREATE TABLE TARGET_DIM_PROJECT (
    PROJECT_ID          NUMBER PRIMARY KEY,
    PROJECT_NAME        VARCHAR2(100),
    CLIENT_NAME         VARCHAR2(100),
    BILLABLE            CHAR(1),
    LEGACY_PROJECT_ID   NUMBER
);

CREATE TABLE TARGET_DIM_DATE (
    DATE_ID             NUMBER PRIMARY KEY,
    CALENDAR_DATE       DATE,
    YEAR                NUMBER,
    MONTH               NUMBER,
    DAY                 NUMBER,
    WEEKDAY_NAME        VARCHAR2(20),
    IS_WEEKEND          CHAR(1),
    LEGACY_DATE         DATE
);

CREATE TABLE TARGET_DIM_ABSENCE_TYPE (
    ABSENCE_TYPE_ID     NUMBER PRIMARY KEY,
    TYPE_NAME           VARCHAR2(50)
);

CREATE TABLE TARGET_DIM_EMPLOYEE_HISTORY (
    HISTORY_ID     NUMBER PRIMARY KEY,
    EMPLOYEE_ID    NUMBER,
    START_DATE     DATE,
    END_DATE       DATE,
    GRADE          VARCHAR2(50),
    DISCIPLINE     VARCHAR2(100),
    LINE_MANAGER   VARCHAR2(100),
    DISTRICT_UNIT  VARCHAR2(100),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES TARGET_DIM_EMPLOYEE(EMPLOYEE_ID)
);

-- Create Fact Table

CREATE TABLE TARGET_FACT_EMPLOYEE_ACTIVITY (
    FACT_ID          NUMBER PRIMARY KEY,
    EMPLOYEE_ID      NUMBER REFERENCES TARGET_DIM_EMPLOYEE(EMPLOYEE_ID),
    DATE_ID          NUMBER REFERENCES TARGET_DIM_DATE(DATE_ID),
    ACTIVITY_TYPE    VARCHAR2(50),
    PROJECT_ID       NUMBER REFERENCES TARGET_DIM_PROJECT(PROJECT_ID),
    DURATION_HOURS   NUMBER(4,2),
    START_TIME       TIMESTAMP,
    END_TIME         TIMESTAMP,
    STATUS           VARCHAR2(20),
    NOTES            VARCHAR2(200),
    SOURCE_ENTRY_ID  NUMBER
);

--  Create Source Staging Tables

-- We import data from Activity Excel using Oracle import
CREATE TABLE SOURCE_ACTIVITY_TEMP (
    FULL_NAME           VARCHAR2(100),
    EMAIL               VARCHAR2(100),
    ACTIVITY_TYPE       VARCHAR2(100),
    START_TIME          TIMESTAMP,
    END_TIME            TIMESTAMP,
    ACTIVITY_DATE       DATE
);

-- We import data from Training Excel using Oracle import
CREATE TABLE SOURCE_TRAINING_TEMP (
    FULL_NAME           VARCHAR2(100),
    EMAIL               VARCHAR2(100),
    ACTIVITY_TYPE       VARCHAR2(100),
    START_TIME          TIMESTAMP,
    END_TIME            TIMESTAMP,
    ACTIVITY_DATE       DATE
);

-- Create Sequences

CREATE SEQUENCE SEQ_EMPLOYEE START WITH 1000;
CREATE SEQUENCE SEQ_PROJECT START WITH 1000;
CREATE SEQUENCE SEQ_DATE START WITH 1000;
CREATE SEQUENCE SEQ_FACT_ACTIVITY START WITH 1000;
CREATE SEQUENCE SEQ_ABSENCE_TYPE START WITH 1000;
CREATE SEQUENCE SEQ_HISTORY START WITH 1000;


-- GRANT SELECT PRIVILEGES FROM SRC_USER TO TGT_USER
GRANT SELECT ON SOURCE_ACTIVITY_TEMP TO TGT_USER;
GRANT SELECT ON SOURCE_TRAINING_TEMP TO TGT_USER;


